name: Build & test affected

on:
  pull_request:
    branches: ['main']

jobs:
  status-checks:
    name: Build & test affected
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable --immutable-cache --check-cache

      - name: Build & test affected
        run: yarn lerna run build,lint,lint:css,test:ci --since=origin/main
